- name: Copy, edit and delete a file
  hosts: ansibletest02
  tasks:
   - name: copy file Manaka.txt
     ansible.builtin.copy:
      src: test1.txt
      dest: /tmp/test1.txt
      mode: '664'
    


   - name: add some data the file manaka.txt
     ansible.builtin.lineinfile:
      path: /tmp/test1.txt
      line: 'updating the file with some text to test'



   - name: deleting the manaka.txt file from test02
     ansible.builtin.file:
      path: /tmp/test1.txt
      state: absent
